<?php

/**
 * Create gutenberg attributes fields
 * @link: https://lazyblocks.com/documentation/blocks-controls/
 */

// load block attributes 
if ( function_exists( 'lazyblocks' ) ) :

   $block_fields = array(
      'id'           => 'lth_blocks', //thay đổi
      'title'        => 'LTH: Blocks', //thay đổi
      'description'  => 'Example block that helps you to get started with Lazy Blocks plugin',
      'icon'         => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" /><rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" /></svg>',
      'slug'         => 'lazyblock/lth-blocks', //thay đổi
      'category'     => 'common'
   );

   lazyblocks()->add_block( array(
      'id' => $block_fields['id'],
      'title' => $block_fields['title'],
      'icon' => $block_fields['icon'],
      'keywords' => array(
      ),
      'slug' => $block_fields['slug'],
      'description' => $block_fields['description'],
      'category' => $block_fields['category'],
      'category_label' => $block_fields['category'],
      'supports' => array(
         'customClassName' => true,
         'anchor' => false,
         'align' => array(
            0 => 'wide',
            1 => 'full',
         ),
         'html' => false,
         'multiple' => true,
         'inserter' => true,
      ),
      'ghostkit' => array(
         'supports' => array(
            'spacings' => false,
            'display' => false,
            'scrollReveal' => false,
            'frame' => false,
            'customCSS' => false,
         ),
      ),
      'controls' => array(
         'control_text' => array(
            'type' => 'text',
            'name' => 'text',
            'default' => '',
            'label' => 'Text',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_textarea' => array(
            'type' => 'textarea',
            'name' => 'text-area',
            'default' => '',
            'label' => 'Text Area',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_number' => array(
            'type' => 'number',
            'name' => 'number',
            'default' => '',
            'label' => 'Number',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'min' => '',
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_range' => array(
            'type' => 'range',
            'name' => 'range',
            'default' => '',
            'label' => 'Range',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'min' => '0',
            'max' => '100',
            'step' => '',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_url' => array(
            'type' => 'url',
            'name' => 'url',
            'default' => '',
            'label' => 'Url',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_email' => array(
            'type' => 'email',
            'name' => 'email',
            'default' => '',
            'label' => 'Email',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_password' => array(
            'type' => 'password',
            'name' => 'password',
            'default' => '',
            'label' => 'Password',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_image' => array(
            'type' => 'image',
            'name' => 'image',
            'default' => '',
            'label' => 'Image',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'preview_size' => 'full',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_gallery' => array(
            'type' => 'gallery',
            'name' => 'gallery',
            'default' => '',
            'label' => 'Gallery',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'preview_size' => 'full',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_file' => array(
            'type' => 'file',
            'name' => 'file',
            'default' => '',
            'label' => 'File',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'allowed_mime_types' => array(
            ),
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_rich_text' => array(
            'type' => 'rich_text',
            'name' => 'rich-text',
            'default' => '',
            'label' => 'Rich Text',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'multiline' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_classic_editor' => array(
            'type' => 'classic_editor',
            'name' => 'classic-editor',
            'default' => '',
            'label' => 'Classic Editor',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_code_editor' => array(
            'type' => 'code_editor',
            'name' => 'code-editor',
            'default' => '',
            'label' => 'Code Editor',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_inner_blocks' => array(
            'type' => 'inner_blocks',
            'name' => 'inner-blocks',
            'default' => '',
            'label' => 'Inner Blocks',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_select' => array(
            'type' => 'select',
            'name' => 'select',
            'default' => '',
            'label' => 'Select',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'choices' => array(
               array(
                  'label' => 'Select 01',
                  'value' => 'select_01',
               ),
               array(
                  'label' => 'Select 02',
                  'value' => 'select_02',
               ),
            ),
            'allow_null' => 'false',
            'multiple' => 'false',
            'output_format' => '',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_radio' => array(
            'type' => 'radio',
            'name' => 'radio',
            'default' => '',
            'label' => 'Radio',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'choices' => array(
               array(
                  'label' => 'Radio 01',
                  'value' => 'radio_01',
               ),
               array(
                  'label' => 'Radio 01',
                  'value' => 'radio_02',
               ),
            ),
            'allow_null' => 'false',
            'multiple' => 'false',
            'output_format' => '',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_checkbox' => array(
            'type' => 'checkbox',
            'name' => 'checkbox',
            'default' => '',
            'label' => 'Checkbox',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'checked' => 'false',
            'alongside_text' => 'Checkbox',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_toggle' => array(
            'type' => 'toggle',
            'name' => 'toggle',
            'default' => '',
            'label' => 'Toggle',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'checked' => 'false',
            'alongside_text' => '',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_color' => array(
            'type' => 'color',
            'name' => 'color',
            'default' => '',
            'label' => 'Color',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'alpha' => 'false',
            'output_format' => '',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_date_time' => array(
            'type' => 'date_time',
            'name' => 'date-time',
            'default' => '',
            'label' => 'Date Time',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'date_time_picker' => 'date_time',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_repeater' => array(
            'type' => 'repeater',
            'name' => 'repeater',
            'default' => '',
            'label' => 'Repeater',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'rows_min' => '1',
            'rows_max' => '',
            'rows_label' => '',
            'rows_add_button_label' => '',
            'rows_collapsible' => 'true',
            'rows_collapsed' => 'true',
            'placeholder' => '',
            'characters_limit' => '',
         ),
         'control_repeater_text' => array(
            'type' => 'text',
            'name' => 'repeater-text',
            'default' => '',
            'label' => 'Text',
            'help' => '',
            'child_of' => 'control_repeater',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
         ),

         ///////////////////////////////

         // cat post          
         'control_select_lth_categories' => array(
            'type' => 'select_dynamic',
            'name' => 'category',
            'default' => '',
            'label' => 'Category',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'select_dynamic_custom_attribute' => 'default_value',
            'placeholder' => '',
            'characters_limit' => '',
            'entity_type' => 'taxonomy',
            'taxonomy_type' => 'category',
            'parent_entity' => '',
            'post_type' => 'post',
         ),   

         // cat product
         'control_select_lth_product_cat' => array(
            'type' => 'select_dynamic',
            'name' => 'product_cat',
            'default' => '',
            'label' => 'Category Product',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'select_dynamic_custom_attribute' => 'default_value',
            'placeholder' => '',
            'characters_limit' => '',
            'entity_type' => 'taxonomy',
            'taxonomy_type' => 'product_cat',
            'parent_entity' => '',
         ),

         // post
         'control_select_lth_posts' => array(
            'type' => 'select_dynamic',
            'name' => 'post',
            'default' => '',
            'label' => 'Post',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'select_dynamic_custom_attribute' => 'default_value',
            'placeholder' => '',
            'characters_limit' => '',
            'entity_type' => 'post',
            'taxonomy_type' => 'category',
            'parent_entity' => '',
            'post_type' => 'post',
         ),

         // product
         'control_select_lth_products' => array(
            'type' => 'select_dynamic',
            'name' => 'product',
            'default' => '',
            'label' => 'Product',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'select_dynamic_custom_attribute' => 'default_value',
            'placeholder' => '',
            'characters_limit' => '',
            'entity_type' => 'post',
            'taxonomy_type' => 'category',
            'parent_entity' => '',
            'post_type' => 'product',
         ),

         // html block
         'control_select_lth_html_blocks' => array(
            'type' => 'select_dynamic',
            'name' => 'html_block',
            'default' => '',
            'label' => 'Html Blocks',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'select_dynamic_custom_attribute' => 'default_value',
            'placeholder' => '',
            'characters_limit' => '',
            'entity_type' => 'post',
            'taxonomy_type' => 'category',
            'parent_entity' => '',
            'post_type' => 'html-blocks',
         ),
      ),
      'code' => array(
         'output_method' => 'html',
         'editor_html' => '',
         'editor_callback' => '',
         'editor_css' => '',
         'frontend_html' => '',
         'frontend_callback' => '',
         'frontend_css' => '',
         'show_preview' => 'always',
         'single_output' => false,
      ),
      'condition' => array(
      ),
   )  );
    
endif;